using ClinicManagementAbp.EntityFrameworkCore;
using Xunit;

namespace ClinicManagementAbp.EntityFrameworkCore;

public class ClinicManagementAbpEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<ClinicManagementAbpEntityFrameworkCoreFixture>
{

}
