using Xunit;

namespace ClinicManagementAbp.EntityFrameworkCore;

[CollectionDefinition(ClinicManagementAbpTestConsts.CollectionDefinitionName)]
public class ClinicManagementAbpEntityFrameworkCoreCollection : ICollectionFixture<ClinicManagementAbpEntityFrameworkCoreFixture>
{

}
